#!/bin/sh

export ARCH=arm
export CROSS_COMPILE=/home/szezso/cm11/prebuilts/gcc/linux-x86/arm/arm-eabi-4.7/bin/arm-eabi-
make VARIANT_DEFCONFIG=msm8930_express_eur_lte_defconfig SELINUX_DEFCONFIG=selinux_defconfig msm8930_express_defconfig
make
